"""Write the current database contents to db/init/02_seed.sql.gz.

The Postgres container runs every *.sql / *.sql.gz in docker-entrypoint-initdb.d on
first boot, so after a live ingest this refreshes the committed snapshot the service
and Q&A layer run against:

    docker compose run --rm ingest
    docker compose run --rm --entrypoint python api scripts/export_seed.py

Output is plain `COPY ... FROM stdin` blocks (what pg_dump emits), generated through
psycopg so it works against any Postgres-compatible server. Generated columns
(filing_chunk.tsv) are recomputed on load.
"""

from __future__ import annotations

import gzip
import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.db.connection import connect  # noqa: E402

# FK-safe order; (table, columns, serial column or None)
TABLES = [
    ("company", ["id", "ticker", "cik", "name", "fiscal_year_end", "sic_description", "updated_at"], "id"),
    (
        "xbrl_fact",
        [
            "id",
            "company_id",
            "taxonomy",
            "concept",
            "unit",
            "period_start",
            "period_end",
            "value",
            "fy",
            "fp",
            "form",
            "accession",
            "filed",
            "frame",
        ],
        "id",
    ),
    (
        "annual_financial",
        [
            "company_id",
            "metric",
            "fiscal_year",
            "period_start",
            "period_end",
            "value",
            "unit",
            "source_concept",
            "derivation",
            "accession",
            "filed",
        ],
        None,
    ),
    (
        "filing",
        [
            "id",
            "company_id",
            "accession",
            "form",
            "filing_date",
            "report_date",
            "fiscal_year",
            "primary_document",
            "url",
            "fetched_at",
        ],
        "id",
    ),
    ("filing_section", ["id", "filing_id", "item", "title", "text", "char_count", "extraction_method"], "id"),
    ("filing_chunk", ["id", "section_id", "seq", "heading", "text"], "id"),
    ("risk_factor", ["id", "filing_id", "seq", "category", "heading", "body"], "id"),
    ("price_daily", ["company_id", "date", "open", "high", "low", "close", "adj_close", "volume", "source"], None),
    ("stock_split", ["company_id", "date", "ratio"], None),
    (
        "insider_transaction",
        [
            "id",
            "company_id",
            "accession",
            "line_no",
            "filing_date",
            "insider_name",
            "insider_cik",
            "relationship",
            "transaction_date",
            "security_title",
            "code",
            "acquired_disposed",
            "shares",
            "price",
            "shares_owned_after",
            "is_10b5_1",
            "ownership",
        ],
        "id",
    ),
    (
        "ingestion_run",
        ["id", "source", "ticker", "started_at", "finished_at", "status", "rows_written", "detail"],
        "id",
    ),
]

ORDER = {  # deterministic output for tables without a serial key
    "annual_financial": ["company_id", "metric", "fiscal_year"],
    "price_daily": ["company_id", "date"],
    "stock_split": ["company_id", "date"],
}


def copy_value(v) -> str:
    """Encode one value in COPY text format."""
    if v is None:
        return r"\N"
    if isinstance(v, bool):
        return "t" if v else "f"
    if isinstance(v, (datetime, date)):
        return v.isoformat()
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, Decimal):
        return format(v, "f")
    s = str(v)
    return s.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r")


def main(out: Path = ROOT / "db" / "init" / "02_seed.sql.gz") -> None:
    with connect() as conn, gzip.open(out, "wt", encoding="utf-8", compresslevel=9) as f:
        f.write("-- Snapshot of ingested data. Generated by scripts/export_seed.py; do not edit.\n")
        f.write("SET client_encoding = 'UTF8';\nBEGIN;\n")
        for table, cols, serial in TABLES:
            order = serial or ", ".join(ORDER[table])
            rows = conn.execute(f"SELECT {', '.join(cols)} FROM {table} ORDER BY {order}").fetchall()
            f.write(f"\nCOPY {table} ({', '.join(cols)}) FROM stdin;\n")
            for r in rows:
                f.write("\t".join(copy_value(r[c]) for c in cols) + "\n")
            f.write("\\.\n")
            if serial:
                f.write(
                    f"SELECT setval(pg_get_serial_sequence('{table}', '{serial}'), "
                    f"COALESCE((SELECT max({serial}) FROM {table}), 1));\n"
                )
            print(f"{table}: {len(rows):,} rows")
        f.write("COMMIT;\nANALYZE;\n")
    print(f"wrote {out} ({out.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
